# Generated by Django 2.1.7 on 2019-04-06 10:59

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('python', 'Python'), ('django', 'Django'), ('restapi', 'RestAPI'), ('ui', 'UI')], max_length=50)),
                ('locations', multiselectfield.db.fields.MultiSelectField(choices=[('hyd', 'Hyderabad'), ('bang', 'Bangalore'), ('che', 'Chennai')], max_length=50)),
                ('shift', multiselectfield.db.fields.MultiSelectField(choices=[('mrng', 'Morning'), ('aftn', 'Afternoon'), ('eve', 'Evening'), ('nite', 'Night')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('date', models.DateField()),
                ('feedback', models.TextField(max_length=500)),
            ],
        ),
    ]
